spring.application.name=ResourceBooking

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/resourcebooking
spring.datasource.username=${DB_username}
spring.datasource.password=${DB_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ResourceBookingSecretKeyForJWTAuthentication2026VerySecure
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG